# Use root/example as user/password credentials
version: '3.1'

services:

  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: bootcamp
      MYSQL_PASSWORD: password
    volumes:
      - ./bootcamp:/home
    ports:
      - 3306:3306